server:
  port: 8088

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  profiles:
    active: dev

github:
  client:
    ID: 47878c9a96cfc358eb6e
    Secret: I will store this on shell env